package entduck

import (
	"context"
	"database/sql"
	"fmt"
	"regexp"
	"strings"
)

var (
	jsonbTypeRE      = regexp.MustCompile(`(?i)\bjsonb\b`)
	onDeleteActionRE = regexp.MustCompile(`(?i)\bON\s+DELETE\s+(?:CASCADE|SET\s+NULL|SET\s+DEFAULT)\b`)
)

// RewriteSQL adapts PostgreSQL SQL generated by ent to the subset DuckDB
// accepts. It skips string literals, quoted identifiers, and comments.
func RewriteSQL(query string) string {
	if query == "" {
		return query
	}
	var b strings.Builder
	start := 0
	for i := 0; i < len(query); {
		switch {
		case query[i] == '\'' || query[i] == '"':
			b.WriteString(rewriteSQLSegment(query[start:i]))
			j := skipQuotedSQL(query, i, query[i])
			b.WriteString(query[i:j])
			i, start = j, j
		case i+1 < len(query) && query[i] == '-' && query[i+1] == '-':
			b.WriteString(rewriteSQLSegment(query[start:i]))
			j := i + 2
			for j < len(query) && query[j] != '\n' {
				j++
			}
			if j < len(query) {
				j++
			}
			b.WriteString(query[i:j])
			i, start = j, j
		case i+1 < len(query) && query[i] == '/' && query[i+1] == '*':
			b.WriteString(rewriteSQLSegment(query[start:i]))
			j := i + 2
			for j+1 < len(query) && !(query[j] == '*' && query[j+1] == '/') {
				j++
			}
			if j+1 < len(query) {
				j += 2
			} else {
				j = len(query)
			}
			b.WriteString(query[i:j])
			i, start = j, j
		case query[i] == '$':
			if tag, ok := dollarQuoteTag(query[i:]); ok {
				b.WriteString(rewriteSQLSegment(query[start:i]))
				j := i + len(tag)
				if k := strings.Index(query[j:], tag); k >= 0 {
					j += k + len(tag)
				} else {
					j = len(query)
				}
				b.WriteString(query[i:j])
				i, start = j, j
			} else {
				i++
			}
		default:
			i++
		}
	}
	b.WriteString(rewriteSQLSegment(query[start:]))
	return b.String()
}

func rewriteSQLSegment(segment string) string {
	segment = onDeleteActionRE.ReplaceAllString(segment, "ON DELETE NO ACTION")
	return jsonbTypeRE.ReplaceAllString(segment, "json")
}

func skipQuotedSQL(query string, idx int, quote byte) int {
	for i := idx + 1; i < len(query); i++ {
		switch query[i] {
		case quote:
			if i+1 < len(query) && query[i+1] == quote {
				i++
				continue
			}
			return i + 1
		case '\\':
			if quote == '\'' && i+1 < len(query) {
				i++
			}
		}
	}
	return len(query)
}

func dollarQuoteTag(s string) (string, bool) {
	if len(s) < 2 || s[0] != '$' {
		return "", false
	}
	for i := 1; i < len(s); i++ {
		switch c := s[i]; {
		case c == '$':
			return s[:i+1], true
		case c == '_' || c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || i > 1 && c >= '0' && c <= '9':
			continue
		default:
			return "", false
		}
	}
	return "", false
}

type execContexter interface {
	ExecContext(context.Context, string, ...any) (sql.Result, error)
}

func dropIndexesForDropColumn(ctx context.Context, conn execContexter, query string) error {
	table, columns, ok := parseDropColumns(query)
	if !ok {
		return nil
	}
	indexes, err := indexesForColumns(ctx, conn, table, columns)
	if err != nil {
		return err
	}
	for _, name := range indexes {
		if _, err := conn.ExecContext(ctx, fmt.Sprintf(`DROP INDEX IF EXISTS "%s"`, strings.ReplaceAll(name, `"`, `""`))); err != nil {
			return fmt.Errorf("entduck: drop index %q before dropping column on %q: %w", name, table, err)
		}
	}
	return nil
}

type queryContexter interface {
	QueryContext(context.Context, string, ...any) (*sql.Rows, error)
}

func indexesForColumns(ctx context.Context, conn execContexter, table string, columns []string) ([]string, error) {
	q, ok := conn.(queryContexter)
	if !ok {
		return nil, nil
	}
	rows, err := q.QueryContext(ctx, `SELECT index_name, sql FROM duckdb_indexes() WHERE table_name = $1`, table)
	if err != nil {
		return nil, fmt.Errorf("entduck: inspect indexes for table %q before DROP COLUMN: %w", table, err)
	}
	defer rows.Close()
	seen := make(map[string]bool)
	var indexes []string
	for rows.Next() {
		var name, ddl string
		if err := rows.Scan(&name, &ddl); err != nil {
			return nil, fmt.Errorf("entduck: scan index metadata for table %q: %w", table, err)
		}
		if seen[name] || !indexDDLReferencesColumn(ddl, columns) {
			continue
		}
		seen[name] = true
		indexes = append(indexes, name)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("entduck: read index metadata for table %q: %w", table, err)
	}
	return indexes, nil
}

func indexDDLReferencesColumn(ddl string, columns []string) bool {
	parts := strings.SplitN(ddl, "(", 2)
	if len(parts) != 2 {
		return false
	}
	exprs := strings.TrimSuffix(parts[1], ")")
	for _, col := range columns {
		for _, candidate := range []string{
			`"` + strings.ReplaceAll(col, `"`, `""`) + `"`,
			col,
		} {
			if containsSQLIdentifier(exprs, candidate) {
				return true
			}
		}
	}
	return false
}

func containsSQLIdentifier(sql, ident string) bool {
	if strings.HasPrefix(ident, `"`) {
		return strings.Contains(sql, ident)
	}
	re := regexp.MustCompile(`(?i)(^|[^a-zA-Z0-9_])` + regexp.QuoteMeta(ident) + `([^a-zA-Z0-9_]|$)`)
	return re.MatchString(sql)
}

func parseDropColumns(query string) (string, []string, bool) {
	tokens := sqlTokens(query)
	if len(tokens) < 5 || !equalFold(tokens[0], "ALTER") || !equalFold(tokens[1], "TABLE") {
		return "", nil, false
	}
	i := 2
	if i < len(tokens) && equalFold(tokens[i], "IF") {
		if i+2 >= len(tokens) || !equalFold(tokens[i+1], "EXISTS") {
			return "", nil, false
		}
		i += 2
	}
	if i >= len(tokens) {
		return "", nil, false
	}
	table := unquoteIdent(tokens[i])
	i++
	var columns []string
	for i < len(tokens) {
		if !equalFold(tokens[i], "DROP") {
			i++
			continue
		}
		i++
		if i < len(tokens) && equalFold(tokens[i], "COLUMN") {
			i++
		}
		if i < len(tokens) && equalFold(tokens[i], "IF") {
			if i+2 >= len(tokens) || !equalFold(tokens[i+1], "EXISTS") {
				continue
			}
			i += 2
		}
		if i >= len(tokens) {
			break
		}
		columns = append(columns, unquoteIdent(tokens[i]))
		i++
	}
	return table, columns, len(columns) > 0
}

func sqlTokens(query string) []string {
	var tokens []string
	for i := 0; i < len(query); {
		switch c := query[i]; {
		case isSQLSpace(c) || c == ',' || c == ';':
			i++
		case c == '\'':
			i = skipQuotedSQL(query, i, c)
		case c == '"':
			j := skipQuotedSQL(query, i, c)
			tokens = append(tokens, query[i:j])
			i = j
		case c == '-' && i+1 < len(query) && query[i+1] == '-':
			i += 2
			for i < len(query) && query[i] != '\n' {
				i++
			}
		case c == '/' && i+1 < len(query) && query[i+1] == '*':
			i += 2
			for i+1 < len(query) && !(query[i] == '*' && query[i+1] == '/') {
				i++
			}
			if i+1 < len(query) {
				i += 2
			}
		default:
			start := i
			for i < len(query) && !isSQLSpace(query[i]) && query[i] != ',' && query[i] != ';' {
				i++
			}
			tokens = append(tokens, query[start:i])
		}
	}
	return tokens
}

func unquoteIdent(ident string) string {
	if len(ident) >= 2 && ident[0] == '"' && ident[len(ident)-1] == '"' {
		return strings.ReplaceAll(ident[1:len(ident)-1], `""`, `"`)
	}
	return ident
}

func equalFold(a, b string) bool {
	return strings.EqualFold(a, b)
}

func isSQLSpace(c byte) bool {
	return c == ' ' || c == '\n' || c == '\r' || c == '\t' || c == '\f'
}

func isPostgresVersionQuery(query string) bool {
	return strings.EqualFold(strings.TrimSpace(query), "SHOW server_version_num")
}

type singleValueRows struct {
	cols  []string
	vals  []any
	ready bool
}

func newSingleValueRows(column string, value any) *singleValueRows {
	return &singleValueRows{cols: []string{column}, vals: []any{value}, ready: true}
}

func (*singleValueRows) Close() error { return nil }
func (*singleValueRows) ColumnTypes() ([]*sql.ColumnType, error) {
	return nil, nil
}
func (r *singleValueRows) Columns() ([]string, error) { return r.cols, nil }
func (*singleValueRows) Err() error                   { return nil }
func (r *singleValueRows) Next() bool {
	if !r.ready {
		return false
	}
	r.ready = false
	return true
}
func (*singleValueRows) NextResultSet() bool { return false }
func (r *singleValueRows) Scan(dest ...any) error {
	if len(dest) != len(r.vals) {
		return fmt.Errorf("entduck: scan expected %d destinations, got %d", len(r.vals), len(dest))
	}
	for i := range dest {
		switch d := dest[i].(type) {
		case *string:
			*d = fmt.Sprint(r.vals[i])
		case *int:
			var n int
			if _, err := fmt.Sscan(fmt.Sprint(r.vals[i]), &n); err != nil {
				return err
			}
			*d = n
		default:
			return fmt.Errorf("entduck: unsupported scan destination %T", dest[i])
		}
	}
	return nil
}
